name: .NET Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        solution:
          - start/GenAiLab.sln
          - complete/GenAiLab.sln

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ matrix.solution }}

    - name: Build solution
      run: dotnet build ${{ matrix.solution }} --no-restore --configuration Release

    - name: Run tests
      run: dotnet test ${{ matrix.solution }} --no-build --verbosity normal
